### ISSUE TITLE
Access to recipe templates for stairs, slabs, 3x3, 2x2, walls, fences, etc would be super-convenient

### ISSUE THREAD

**Issue by noobanidus** [tterrag1098/Registrate#1]
Basically as it says in the title. Either just being able to access functions that are automatically fed a consume, i.e.,

` .recipe(ctx -> ctx.getProvider().stairs(Blocks.STONE, true))`

or something more complex would be great. (Boolean parameter for stonecutter)

**Comment by tterrag1098** [comment]
I have some helpers for this already [in Tropicraft](https://github.com/Tropicraft/Tropicraft/blob/9e5ba2b8e45b3cfd7d5207154140e6e965bdc2fb/src/main/java/net/tropicraft/core/common/data/TropicraftRecipeProvider.java#L271-L401), I can definitely pull them over.

**Comment by noobanidus** [comment]
Some warnings: if your output item for things like smelting or blasting happens to be the same as a Minecraft item, the actual recipe name then (for some reason) gets placed into the Minecraft data folder's recipe folder, instead of in your own.

This is obviously only relevant to things like recycling recipes, but: I believe I was using something similar to your Tropicraft helpers, but it resulted in: https://github.com/MysticMods/MysticalWorld/issues/101 In this case it was "gold_nugget_from_blasting", which overrode a similarly named Minecraft recipe.

Nothing huge but something to consider, my solution was [this](https://github.com/MysticMods/MysticalLib/blob/1.14/src/main/java/epicsquid/mysticallib/data/DeferredRecipeProvider.java#L33) and allow providing a namespace. 

I'm not sure if by-default wrapping the the namespace output in the modid is a good idea or not. Honestly, I get a bit confused sometimes about which recipes are supposed to go where.

**Comment by nikita488** [comment]
It will be cool to have a helper for this kind of recipe:
![image](https://user-images.githubusercontent.com/6237881/79072296-f7cebf00-7ce8-11ea-9e7b-e469efda0255.png)
I don't know how to name it, maybe like 2x2?
Also, I think safeId and safeName methods in RegistrateRecipeProvider should be public so we can use them in our recipes as well.

**Comment by tterrag1098** [comment]
Added.

**Comment by tterrag1098** [comment]
If there are more specific helper requests, please don't hesitate to make new issues. I'm closing this because I think the existing helpers are good enough for 1.0.
