### ISSUE TITLE
[Improvement] Catch & improve error messages to clarify what RegistryEntry, etc, is affected

### ISSUE THREAD

**Issue by noobanidus** [tterrag1098/Registrate#10]
Specifically: https://gist.github.com/noobanidus/8177fab4bf9c5af1c349b15caff0f435

The issue here is that the default item model builder was relying on the name of the item being the texture, while I had made a mistake in the code so that it was providing "copper" instead of "copper_ingot".

Unfortunately, given the number of copper-related things and not having even a reference point as to whether it was a block's default item model or whether it was an item's default item, I just basically had to go through the entire relevant code until I spotted it.

If it was possible to catch and then re-print errors but also print which registry entry was triggering them, that would be super-useful.

---

While not specific to this originally: https://gist.github.com/noobanidus/ca31eba9620fbfdacd3a23087f63f01b

This error occurred because I had two separate "GEMS" tags, and somehow both of them were "forge:gems" instead of one being "forge:gems" and the other being "mysticalworld:gems". I don't really know if there's any way to give more information in this case as it was being defined thus:

```java
  static {
    REGISTRATE.addDataGenerator(ProviderType.ITEM_TAGS, p -> {
      ItemBuilder b = new ItemBuilder(p);
      b.additional(Tags.Items.ORES).add(MWTags.Items.AMETHYST_ORE, MWTags.Items.COPPER_ORE, MWTags.Items.LEAD_ORE, MWTags.Items.QUICKSILVER_ORE, MWTags.Items.SILVER_ORE, MWTags.Items.TIN_ORE);

      b.add(MWTags.Items.AUBERGINE, ModItems.AUBERGINE);
      b.add(MWTags.Items.EGGPLANT, MWTags.Items.AUBERGINE);
```

Where ItemBuilder, etc, are my custom classes. However, the error message doesn't really have any mention of where in the Registrate process things have gone wrong.

**Comment by tterrag1098** [comment]
Fixed via https://github.com/tterrag1098/Registrate/commit/169bb27c3aaabdd26b38d7d20e93ea91474a362e
