### ISSUE TITLE
Registrate does not work in a project using official mappings (MojMaps)

### ISSUE THREAD

**Issue by TheOnlyTails** [tterrag1098/Registrate#28]
I have a project that uses official mappings, and after I was done converting all my items and blocks over to the Registrate system, it causes Forge to throw an extremely long `StackOverflowException`, like in the following [log](https://gist.github.com/b646ed380fa1696e8ecfcda8bc982f7b).

From talking to nikita488 on your server, I understand this issue can be resolved by simply switching Registrate over to use the official mappings (at least for 1.16).

I understand this would cause problems with MCP projects, but I would argue that it's fine since Forge now considers official mappings the preferred ones.

**Comment by noobanidus** [comment]
This is invalid, there are other solutions than just converting to mojmap, which has its own issues. See #29

**Comment by tterrag1098** [comment]
Fixed
