### ISSUE TITLE
Difficulty adding additional non-object-related language keys

### ISSUE THREAD

**Issue by noobanidus** [tterrag1098/Registrate#3]
I've got a couple of messages sending to the client, but I can't find any way to actually manually add this; it overrides (rather than combines with) the language file defined in the non-generated resources.

**Comment by noobanidus** [comment]
```java
  static {
   REGISTRATE.item("ritual_knife", Item::new).properties(PROPS).addData(ProviderType.LANG, ctx -> {
     ctx.getProvider().add("key", "value");
   });
  }
```

This is the only vague semblance that I've managed to get; it feels... not particularly good.

**Comment by tterrag1098** [comment]
Yep, I have come across the same limitation. Definitely want to make this use case easier.
