### ISSUE TITLE
Compiled Registrate

### ISSUE THREAD

**Issue by Sl1pstr3am** [tterrag1098/Registrate#30]
Hi, sorry if this issue is unusual. Just wondering where I can find the latest compiled jar? I'm using a fabric mod that has Registrate as a dependency, and I tried building the source of this mod, but I got a weird gradle error. If someone could link me to that, that would be great. Thanks

**Comment by ChampionAsh5357** [comment]
Registrate is a forge library? I don't know why a fabric mod would be shading it or how most of it would be useable without a bunch of rewrites.

**Comment by Sl1pstr3am** [comment]
> Registrate is a forge library? I don't know why a fabric mod would be shading it or how most of it would be useable without a bunch of rewrites.

Honestly, I have no idea either. The WIP Fabric port of create has it listed as a dependency. This seems to be the only "Registrate" mod out there, so I don't really know. There doesn't seem to be much information on the Create repo either, so I'm not really sure what's going on. I even tried removing the dependency from the fabric.mod.json file, but that just leads to a crash. If you're familiar with any other Registrate mods out there, then maybe that's what it is? Other than that, I don't know.

**Comment by tterrag1098** [comment]
They have their own repository with a port, there is no official fabric port, you'd have to ask the create refabricated team.
