### ISSUE TITLE
Faulty FluidBuilder Source Check

### ISSUE THREAD

**Issue by PepperCode1** [tterrag1098/Registrate#32]
After updating Registrate from 1.0.4 to 1.0.5, the mod that was using it failed to start. The issue is that the `FluidBuilder.bucket(factory)` method can't be called if the `.source` method wasn't called, so it fails if it uses the default source but not the default bucket. This check was added in 1.0.5.

Additionally, the non-default bucket was used to make it have a max stack size of one. I think making this part of the default bucket creation could be a good idea.

**Comment by tterrag1098** [comment]
Fixed via 013f4658f5848089805291737c37d63fa35d8574
