### ISSUE TITLE
Something wrong with compilate JAR

### ISSUE THREAD

**Issue by Potochnyy** [tterrag1098/Registrate#39]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\Users\knizh\OneDrive\Desktop\Registrate-1.18\build.gradle' line: 30

* What went wrong:
A problem occurred evaluating root project 'Registrate'.
> Cannot invoke method describe() on null object

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring root project 'Registrate'.
> Missing 'minecraft' dependency.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
<-------------> 0% WAITING
> IDLE

**Comment by tterrag1098** [comment]
Use git properly and clone the repository, and this won't be an issue.
