### ISSUE TITLE
[Bug] Item CreativeModeTabModifier callback missing reference to Item being constructed

### ISSUE THREAD

**Issue by ApexModder** [tterrag1098/Registrate#56]
when using the following method, you are not given a reference to the current item being constructed in the callback.

https://github.com/tterrag1098/Registrate/blob/d5f97f5a105164276e2d287b08735659881ba3db/src/main/java/com/tterrag/registrate/builders/ItemBuilder.java#L138-L141

This means it is not possible to add the item to the creative mode tab via this callback.

Example showcasing attempt to add item to `OP_BLOCKS` tab only when player has permission, missing reference to be able to call the needed `.accept()` method.

![image](https://github.com/tterrag1098/Registrate/assets/29412632/3b9f6e62-f1d5-4cba-9605-5fdf924f5ca2)

**Comment by tterrag1098** [comment]
Merged
