### ISSUE TITLE
AdvancementProvider title and desc doesn't accept TextComponent nesting

### ISSUE THREAD

**Issue by Drullkus** [tterrag1098/Registrate#6]
`RegistrateAdvancementProvider` doesn't have helpers for making nested `TextTranslationComponent`s while adding lang keys. Currently there exists the option for just setting `adv.desc("root", "Get an egg.")` but I'd like to be able to do `adv.desc("root", "Get an %s.", new TranslationTextComponent(Items.EGG.getTranslationKey()))`

**Comment by tterrag1098** [comment]
On second thought, I'm not sure how this really makes sense. Format arguments are to be used when a lang entry is used for multiple applications, but here you are generating a lang entry. So by definition it can't be done more than once for a given key. It would probably be better to just create a new text component from the result of this method.

```java
new TranslationTextComponent(adv.desc("root", "Get an %s.").getKey(), new TranslationTextComponent(Items.EGG.getTranslationKey()));
```
