### ISSUE TITLE
Strip out testmod data, etc, including advancements

### ISSUE THREAD

**Issue by noobanidus** [tterrag1098/Registrate#7]
Although the devcraft people have grown fond of "Test Advancement: Obtain an egg."

https://gfycat.com/DazzlingVigilantJunco

**Comment by tterrag1098** [comment]
egg.

**Comment by noobanidus** [comment]
I need to add that back in as a challenge where you have to collect a chicken egg, collect raw chicken, cook raw chicken into cooked chicken, eat cooked chicken...
