### ISSUE TITLE
[Feature] A few useful methods for BlockBuilder & ItemBuilder

### ISSUE THREAD

**Issue by nikita488** [tterrag1098/Registrate#8]
1. It might be useful to have a **blockColor** method in BlockBuilder that will allow auto-register block color for the specified block.
2. Same as number 1 but for items: **itemColor** method in ItemBuilder (auto-register item colors for items)
3. _Only for 1.15.*_: **renderLayer** method in BlockBuilder that will allow setting RenderType for the specified block.

**Comment by tterrag1098** [comment]
I'm of two minds about this proposal. First off, implementing it in a server-safe way will be challenging and potentially very clumsy to use. But also, I'm not sure that I want to mix in clientside concerns to the registration process. You could say that model/lang generators already do this, but nothing there is actually unsafe for the server (it's not even executed during a normal game launch). I'll have to evaluate how useful this would be and if it would be worth the difficulties.

**Comment by tterrag1098** [comment]
I've implemented a render layer setter now. It was, as expected, tricky to make safe. But thanks to the pretty tightly scoped nature of render layers (all accessible via a static method) I can recommend a way that is 100% safe afaik. Still not sure I want to handle tints yet, but I'll see how it works out.
