### ISSUE TITLE
[1.15.1] Crash when trying to generate data

### ISSUE THREAD

**Issue by nikita488** [tterrag1098/Registrate#9]
Using Registrate **MC1.15.1-0.0.1.1** from maven. It works fine when I just run and play the game, but when I try to generate data using **"runData"** run configuration, it crashes.
Crash report: https://pastebin.com/5zDUCW57

**Comment by tterrag1098** [comment]
This is a breaking forge change, I'll have to update.

**Comment by tterrag1098** [comment]
Fixed via https://github.com/tterrag1098/Registrate/commit/1733e57cb8b7b65ecbbf3be61c0be02fb70b252f
